#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/DAEMON,v 1.6.2.1.8.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
