#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/dmesg,v 1.7.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: dmesg
# REQUIRE: mountcritremote cleanvar
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="dmesg"
rcvar="dmesg_enable"
dmesg_file="/var/run/dmesg.boot"
start_cmd="do_dmesg"
stop_cmd=":"

do_dmesg()
{
	rm -f ${dmesg_file}
	( umask 022 ; /sbin/dmesg $rc_flags > ${dmesg_file} )
}

load_rc_config $name
run_rc_command "$1"
