#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/FILESYSTEMS,v 1.2.12.1.8.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal zfs

#	This is a dummy dependency, for services which require file systems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other file systems than /.
