#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ftp-proxy,v 1.3.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: ftp-proxy
# REQUIRE: DAEMON pf
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpproxy"
rcvar="ftpproxy_enable"
command="/usr/sbin/ftp-proxy"

load_rc_config $name
run_rc_command "$1"
