#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/gssd,v 1.1.2.1.8.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: gssd
# REQUIRE: root
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="gssd"

load_rc_config $name
rcvar="gssd_enable"
command="${gssd:-/usr/sbin/${name}}"
eval ${name}_flags=\"${gssd_flags}\"
run_rc_command "$1"
