#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/LOGIN,v 1.6.2.1.8.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
