#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/mrouted,v 1.11.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: mrouted
# REQUIRE: netif routing cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar="mrouted_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
