#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/msgs,v 1.2.22.1.8.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: msgs
# REQUIRE: LOGIN

# Make a bounds file for msgs(1) if there isn't one already
#
if [ -d /var/msgs -a ! -f /var/msgs/bounds -a ! -L /var/msgs/bounds ]; then
	echo 0 > /var/msgs/bounds
fi
