#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/newsyslog,v 1.7.2.3.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: newsyslog
# REQUIRE: cleanvar mountcritremote

. /etc/rc.subr

name="newsyslog"
rcvar="newsyslog_enable"
required_files="/etc/newsyslog.conf"
command="/usr/sbin/${name}"
start_cmd="newsyslog_start"
stop_cmd=":"

newsyslog_start()
{
	check_startmsgs && echo -n 'Creating and/or trimming log files'
	${command} ${rc_flags}
	check_startmsgs && echo '.'
}

load_rc_config $name
run_rc_command "$1"
