#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rwho,v 1.6.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="rwhod"
rcvar="rwhod_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
