#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/adjkerntz,v 1.6.10.1.8.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: adjkerntz
# REQUIRE: FILESYSTEMS random
# BEFORE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="adjkerntz"
start_cmd="adjkerntz -i"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
