#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/bootparams,v 1.8.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
rcvar="bootparamd_enable"
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
