#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/devd,v 1.11.2.3.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: devd
# REQUIRE: netif network_ipv6
# BEFORE: NETWORKING mountcritremote
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="devd"
rcvar="devd_enable"
command="/sbin/${name}"

start_precmd=${name}_prestart
stop_precmd=find_pidfile

find_pidfile()
{
	if get_pidfile_from_conf pid-file /etc/devd.conf; then
		pidfile="$_pidfile_from_conf"
	else
		pidfile="/var/run/${name}.pid"
	fi
}

devd_prestart ()
{
	find_pidfile

	# If devd is disabled, turn it off in the kernel to avoid memory leaks.
	if ! checkyesno ${rcvar}; then
	    $SYSCTL hw.bus.devctl_disable=1
	fi
}

load_rc_config $name
run_rc_command "$1"
