#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/NETWORKING,v 1.17.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netoptions routing network_ipv6 ppp ipfw
# REQUIRE: defaultroute routed mrouted route6d mroute6d resolv
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
