#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.14.2.3.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
rcvar="rpcbind_enable"
command="/usr/sbin/${name}"

stop_postcmd='/bin/rm -f /var/run/rpcbind.*'

load_rc_config $name
run_rc_command "$1"
