#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/SERVERS,v 1.8.2.3.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig savecore watchdogd

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
