#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/timed,v 1.7.2.2.2.2 2012/11/17 08:24:38 svnexp Exp $
#

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
rcvar="timed_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
