#!/bin/sh
#
# $P4: //depot/projects/trustedbsd/openbsm/etc/audit_warn#3 $
# $FreeBSD: src/contrib/openbsm/etc/audit_warn,v 1.2.12.1.8.2 2012/11/17 08:24:36 svnexp Exp $
#
logger -p security.warning "audit warning: $@"
